[package]
name = "anzen"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "az"
path = "src/main.rs"

[dependencies]
chrono = "0.4.40"
clap = { version = "4.5.32", features = ["derive"]}
git2 = "0.20.1"
gpgme = "0.11.0"
prettytable-rs = "0.10.0"
